# Generated by Django 3.0.3 on 2020-02-08 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 2, 8, 12, 51, 16, 421862)),
        ),
    ]
